(set-face-italic-p 'italic nil)
(set-face-bold-p 'bold nil)
(setq solarized-italic nil)
(setq solarized-termcolors 256)
(setq solarized-degrade t)
;; (set-frame-parameter nil 'background-mode 'light)
;; (set-terminal-parameter nil 'background-mode 'light)
(color-theme-solarized)
