(require 'tex-mode)

;; fill paragraph using punctuation
(defun fill-using-punctuation ()
  (interactive)
  (save-excursion
    (progn (mark-paragraph)
           (let ((begin (region-beginning))
                 (end (region-end)))
             (replace-regexp "\\([.,?:;!]\\)\s+" "\\1
" nil begin end)))))

(defun my/load-latex ()
  (interactive)
  (add-to-list 'load-path "~/.emacs.d/packages/auctex")
  (load "auctex.el" nil t t)
  (load "preview-latex.el" nil t t)
  (LaTeX-mode)
  (add-to-list 'load-path "~/.emacs.d/packages/auctex-latexmk")
  (require 'auctex-latexmk)
  (auctex-latexmk-setup)
  ;; (set-face-attribute 'font-lock-constant-face nil :foreground "color-212")
  ;; ;(set-face-attribute 'font-lock-keyword-face nil :foreground "blue")
  ;; (set-face-attribute 'font-lock-type-face nil :foreground "color-73")
  ;; (set-face-attribute 'font-lock-function-name-face nil :foreground "color-210")
  ;; (set-face-attribute 'font-latex-sedate-face nil :foreground "purple")
  ;; (set-face-attribute 'font-latex-italic-face nil :foreground "magenta")
  ;; (set-face-attribute 'font-latex-bold-face nil :foreground "magenta")
  ;; (set-face-attribute 'font-latex-sectioning-2-face nil :foreground "color-206")
  ;; (set-face-attribute 'font-latex-sectioning-3-face nil :foreground "color-208")
  ;; (set-face-attribute 'font-latex-sectioning-5-face nil :foreground "color-214")
  ;; (set-face-attribute 'font-latex-math-face nil :foreground "color-41")
  ;; (set-face-attribute 'font-latex-warning-face nil :foreground "white")
  (define-key TeX-mode-map (kbd "M-J") '(lambda ()
					  (interactive)
					  (if (= 0 (current-column))
					      (insert "%\n")
					    (insert "\n%\n"))))
  (define-key TeX-mode-map (kbd "C-c C-c") '(lambda ()
					      (interactive)
					      (TeX-command "LatexMk" 'TeX-master-file 0)))
  (define-key TeX-mode-map (kbd "C-c q") 'fill-using-punctuation)
  (define-key TeX-mode-map (kbd "C-c C-a") '(lambda ()
					      (interactive)
					      (TeX-command "View" 'TeX-master-file 0)))
  (setq auctex-latexmk-inherit-TeX-PDF-mode t)
  (setq-default TeX-command-default "LatexMk")
  (setq TeX-view-program-selection '((output-pdf "zathura")))
  (setq TeX-view-program-list '(("zathura" ("zathura" " --fork" " %o"))))
  (setq-default TeX-master (car (split-string (buffer-name) "\\."))))


(add-hook 'tex-mode-hook 'my/load-latex)
